### ISSUE TITLE
NPE when used with Maven release plugin

### ISSUE THREAD

**Issue by dscorbett** [c0d3d/plugin-repeater-maven-plugin#7]
The Maven release plugin normalizes empty XML elements to the self-closing form: `<foo></foo>` to `<foo />`. The repeater apparently sees the former as an empty string and the latter as `null`. That causes a `NullPointerException` [in `com.nlocketz.plugins.Util#filter`](https://github.com/c0d3d/plugin-repeater-maven-plugin/blob/plugin-repeater-maven-plugin-0.0.6/src/main/java/com/nlocketz/plugins/Util.java#L28) when it tries to replace a variable expression with `null`.

The work-around is it add a comment within the empty element so the release plugin can’t collapse it.

**Comment by c0d3d** [comment]
@dscorbett, I think this should fix it: https://github.com/c0d3d/plugin-repeater-maven-plugin/tree/empty-tag
This is what you were talking about right?

**Comment by dscorbett** [comment]
Essentially, yes. I would refactor it to not call `get` twice though.

(... must... resist temptation... to comment on the commit message...)

**Comment by c0d3d** [comment]
I see you didn't have the will power ....

This is in 0.0.7 which I've just released.
